import { execFile } from 'child_process'; import { promisify } from 'util'; import fs from 'fs/promises'; import path from 'path'; import { S3Client,PutObjectCommand,ListObjectsV2Command,DeleteObjectCommand } from '@aws-sdk/client-s3';
const exec=promisify(execFile); const dir=process.env.BACKUP_DIR||'./backups';
function parseDb(){const u=new URL(process.env.DATABASE_URL);return {host:u.hostname,port:u.port||'5432',user:decodeURIComponent(u.username),password:decodeURIComponent(u.password),database:u.pathname.slice(1)};}
function s3(){if(!process.env.S3_BUCKET)return null;return new S3Client({region:process.env.S3_REGION||'us-east-1',endpoint:process.env.S3_ENDPOINT||undefined,forcePathStyle:process.env.S3_FORCE_PATH_STYLE==='true',credentials:process.env.S3_ACCESS_KEY_ID?{accessKeyId:process.env.S3_ACCESS_KEY_ID,secretAccessKey:process.env.S3_SECRET_ACCESS_KEY}:undefined});}
export async function createBackup(){await fs.mkdir(dir,{recursive:true});const d=new Date();const stamp=d.toISOString().replace(/[:T]/g,'-').replace(/\.\d{3}Z$/,'');const file=`backup_${stamp}.sql.gz`;const out=path.join(dir,file);const db=parseDb();await exec('bash',['-lc',`PGPASSWORD=${JSON.stringify(db.password)} pg_dump -h ${JSON.stringify(db.host)} -p ${JSON.stringify(db.port)} -U ${JSON.stringify(db.user)} -d ${JSON.stringify(db.database)} | gzip > ${JSON.stringify(out)}`]);const client=s3();if(client){await client.send(new PutObjectCommand({Bucket:process.env.S3_BUCKET,Key:`backups/${file}`,Body:await fs.readFile(out),ContentType:'application/gzip'}));}await cleanup();return {file,path:out};}
export async function listBackups(){await fs.mkdir(dir,{recursive:true});const files=await fs.readdir(dir);return Promise.all(files.filter(f=>f.endsWith('.sql.gz')).sort().reverse().map(async f=>{const st=await fs.stat(path.join(dir,f));return {file:f,size:st.size,createdAt:st.mtime};}));}
export function backupPath(file){if(!/^backup_[\w.-]+\.sql\.gz$/.test(file))throw new Error('Nome de backup inválido');return path.join(dir,file);}
export async function restoreBackup(file){const db=parseDb();const input=backupPath(file);await fs.access(input);await exec('bash',['-lc',`gunzip -c ${JSON.stringify(input)} | PGPASSWORD=${JSON.stringify(db.password)} psql -h ${JSON.stringify(db.host)} -p ${JSON.stringify(db.port)} -U ${JSON.stringify(db.user)} -d ${JSON.stringify(db.database)}`]);}
async function cleanup(){const localDays=Number(process.env.BACKUP_RETENTION_DAYS||7);const cutoff=Date.now()-localDays*86400000;for(const b of await listBackups()){if(new Date(b.createdAt).getTime()<cutoff)await fs.unlink(backupPath(b.file)).catch(()=>{});}const client=s3();if(client){const cloudCutoff=Date.now()-Number(process.env.CLOUD_BACKUP_RETENTION_DAYS||30)*86400000;const listed=await client.send(new ListObjectsV2Command({Bucket:process.env.S3_BUCKET,Prefix:'backups/'}));for(const o of listed.Contents||[]){if(o.LastModified?.getTime()<cloudCutoff)await client.send(new DeleteObjectCommand({Bucket:process.env.S3_BUCKET,Key:o.Key}));}}}
