ALTER TYPE "TipoEvolucao" ADD VALUE IF NOT EXISTS 'TRIAGEM';

ALTER TABLE "profissionais" ADD COLUMN "departamentoPrincipalId" TEXT;
ALTER TABLE "escalas" ADD COLUMN "departamentoId" TEXT;

CREATE TABLE "departamentos" (
  "id" TEXT NOT NULL,
  "nome" TEXT NOT NULL,
  "ativo" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "departamentos_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "indisponibilidades_profissionais" (
  "id" TEXT NOT NULL,
  "profissionalId" TEXT NOT NULL,
  "inicio" TIMESTAMP(3) NOT NULL,
  "fim" TIMESTAMP(3),
  "indeterminado" BOOLEAN NOT NULL DEFAULT false,
  "motivo" TEXT,
  "ativo" BOOLEAN NOT NULL DEFAULT true,
  "createdBy" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "encerradoEm" TIMESTAMP(3),
  "encerradoBy" TEXT,
  CONSTRAINT "indisponibilidades_profissionais_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "alertas_escala" (
  "id" TEXT NOT NULL,
  "profissionalId" TEXT,
  "titulo" TEXT NOT NULL,
  "mensagem" TEXT NOT NULL,
  "detalhes" JSONB,
  "lidoPor" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "alertas_escala_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "departamentos_nome_key" ON "departamentos"("nome");
CREATE INDEX "departamentos_ativo_nome_idx" ON "departamentos"("ativo","nome");
CREATE INDEX "escalas_departamentoId_idx" ON "escalas"("departamentoId");
CREATE INDEX "indisponibilidades_profissionais_profissionalId_ativo_inicio_idx" ON "indisponibilidades_profissionais"("profissionalId","ativo","inicio");
CREATE INDEX "alertas_escala_createdAt_idx" ON "alertas_escala"("createdAt");

ALTER TABLE "profissionais" ADD CONSTRAINT "profissionais_departamentoPrincipalId_fkey"
  FOREIGN KEY ("departamentoPrincipalId") REFERENCES "departamentos"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "escalas" ADD CONSTRAINT "escalas_departamentoId_fkey"
  FOREIGN KEY ("departamentoId") REFERENCES "departamentos"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "indisponibilidades_profissionais" ADD CONSTRAINT "indisponibilidades_profissionais_profissionalId_fkey"
  FOREIGN KEY ("profissionalId") REFERENCES "profissionais"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "alertas_escala" ADD CONSTRAINT "alertas_escala_profissionalId_fkey"
  FOREIGN KEY ("profissionalId") REFERENCES "profissionais"("id") ON DELETE SET NULL ON UPDATE CASCADE;

INSERT INTO "departamentos" ("id","nome","ativo","createdAt","updatedAt") VALUES
('dept-001','PRONTO SOCORRO - SUTURA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-002','PRONTO SOCORRO - CLASSIFICAÇÃO DE RISCO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-003','PRONTO SOCORRO - SALA VERMELHA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-004','PRONTO SOCORRO - LEITO DIA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-005','PRONTO SOCORRO - MEDICAÇÃO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-006','PRONTO SOCORRO - URGÊNCIA/EMERGÊNCIA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-007','AMBULATÓRIO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-008','SADT/IMAGENS - RAIO X',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-009','SADT/IMAGENS - TOMOGRAFIA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-010','SADT/IMAGENS - ULTRASSONOGRAFIA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-011','SADT/IMAGENS - ELETROCARDIOGRAMA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-012','SADT/IMAGENS - ECOCARDIOGRAMA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-013','LABORATÓRIO - SALA DE COLETA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-014','LABORATÓRIO - ANÁLISES CLÍNICAS',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-015','MULTIPROFISSIONAL',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-016','UTI',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-017','CENTRO CIRÚRGICO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-018','TECNOLOGIA DA INFORMAÇÃO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-019','FARMÁCIA CENTRAL',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-020','CAF',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-021','ALMOXARIFADO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-022','CME',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-023','NUTRIÇÃO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-024','CLINICA CIRÚRGICA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-025','CLINICA MÉDICA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-026','FATURAMENTO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-027','FINANCEIRO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-028','INDICADORES',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-029','QUALIDADE',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-030','SESMT',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-031','SCIH',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-032','GESTÃO DE PESSOAS/RH',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-033','ENGENHARIA CLÍNICA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-034','MANUTENÇÃO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-035','PATRIMÔNIO',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-036','ENERGIA VERDE',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('dept-037','ROUPARIA',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("nome") DO NOTHING;
